# -*- coding: utf-8 -*-
"""Dino_Nuggets_Based_On_Chatbot_Demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLRvI6JobRr6QQGCUujDXnxpFAFJ8W6L

# definitions
* tensor: esentially the same as an array but optimized to run on the GPU with large sets of data
  * ex:

```
tensor_example_1 = [0.34, 0.91, 1]
tensor_example_2 = [
  [0.34, 0.91, 1],
  [0.1, 0.98, 0.01],
  [0.32, 0.65, 0.93]
]
```
"""

# Basic Knowledge-Base Chatbot
# - Embeds a small knowledge base with SentenceTransformers
# - Retrieves top-k relevant facts using cosine similarity
# - Generates an answer with FLAN-T5 (using model/tokenizer directly for maximum compatibility)

import numpy as np
import torch
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# 1) Knowledge base
knowledge_base = [
    "Dinosaurs are a group of reptiles that have lived on Earth for about 245 million years.",
    "In 1842, the English naturalist Sir Richard Owen coined the term Dinosauria, derived from the Greek deinos, meaning ‘fearfully great,’ and sauros, meaning ‘lizard.’",
    "Dinosaur fossils have been found on all seven continents.",
    "All non-avian dinosaurs went extinct about 66 million years ago.",
    "There are roughly 700 known species of extinct dinosaurs.",
    "Modern birds are a kind of dinosaur because they share a common ancestor with non-avian dinosaurs.",
    "To discover how organisms lived in the past, paleontologists look for clues preserved in ancient rocks—the fossilized bones, teeth, eggs, footprints, teeth marks, leaves, and even dung of ancient organisms.",
    "Until recently it was believed that feathers were unique to birds. Recent discoveries, however, have unearthed evidence for feathered non-avian dinosaurs.",
    "Triceratops had hundreds of teeth that formed a solid ‘wall’ with sharp ridges. The teeth were used to chop off vegetation.",
    "Some of the most commonly known dinosaurs include: Tyrannosaurus Rex, Triceratops, Stegosaurus, Brontosaurus, and Velociraptor.",
    "Feathers evolved before flight and may have functioned as insulation to keep dinosaurs warm, or for display as a way to attract mates.",
    "Feathers evolved before flight and may have functioned as insulation to keep dinosaurs warm, or for display as a way to attract mates.",
    "‘Tyrannosaurus’ is Greek for ‘tyrant lizard,’ and ‘rex’ means ‘king’ in Latin. So, Tyrannosaurus Rex was ‘King of the Tyrant Lizards.’",
    "Tyrannosaurus Rex  lived about 66–68 million years ago during the Cretaceous Period in the western United States, including Montana and Wyoming.",
    "Tyrannosaurus Rex skulls and teeth reveal that it was a meat eater, and judging from its size, it could have eaten whatever animal it could catch or scavenge.",
    "The word ‘Tyrannosaur’ refers to all members of the Tyrannosauroidea superfamily. More than 22 species of Tyrannosaurs are known to exist, and more are discovered every year.",
    "The Troodon was considered the Einstein of dinosaurs, with a relatively large brain for its body. Fossil evidence suggests great senses. Such as excellent eyesight, smell, and keen hearing.",
    "The Trodon’s brain may have been the size of a golf ball, but it was the smartest dinosaur of its time. Compared to its size which was usually half the size of a human and only 1-2 meters long. A golf ball size brain was large considering their body mass. ",
    "The Troodon may have also been called the Stenonychosaurus, and was very similar to our birds. This dinosaur was also considered an omnivore.",
    "Are you curious about what dinosaur you may be, here's a short quiz to help you find out: https://www.nhm.ac.uk/discover/what-dinosaur-are-you.html",
    "Abydosaurus mcintoshi is a sauropod dinosaur from the Early Cretaceous period (approximately 105 million years ago).",
    "Abydosaurus mcintoshi was first discovered in the Cedar Mountain Formation, Utah, USA. ",
    "Acristavus gagslarsoni is from the late Late Cretaceous period. ",
    "Acristavus gagslarsoni is an uncrested, brachylophosurine hadrosaurid relative of Brachylophosaurus (short-crested lizard) and Maisaurus (the good mother lizard).",
    "Acristavus gagslarsoni is from the late Late Cretaceous period. ",
    "Acristavus gagslarsoni was described in 2011 from the Two Medicine Formation of Montana and described from correlative strata in the upper part of the Reynolds Point Member of the Wahweap Formation in Utah.",
    "Acrocanthosaurus was a giant carnivore from the middle cretaceous period. ",
    "We don’t know of the dinosaurs that lived in the jungle or mountain area since fossils were formed in or near rivers. ",
    "The fossils we see today were buried by mud or sediment and if they did not die near or in the water, they were washed into a river with heavy rain. ",
    "Due to the weight and pressure of the ongoing build up of mud and rock, they are turned into sedimentary rock. While this is happening water seeps into their bones and teeth, turning them into stone as it leaves behind minerals. ",
    "The water leaves mineral crystals behind in spaces in the bones, this is why dinosaur fossils often have a sponge or or honey comb like texture. ",
    "Utahraptor ostrommaysi is one of Utah's more famous new dinosaurs and designated as the State dinosaur in 2018",
    "Utahraptor skeletal sites are only known in Grand County in a belt of outcrop along the east and north sides of Arches National Park",
    "Utahraptor ostrommaysi was from the late cretaceous period",
    "Hagryphus is an oviraptor.",
    "The hagryphus is from the late cretaceous period. ",
    "Deinonychus is the best known of North America's dromaeosaurids, or raptors.",
    "In Utah, deinonychus is mostly known from teeth collected in the Ruby Ranch Member of the Cedar Mountain Formation.",
    "Deinonychid tracks (track name Dromaeosaurpus) have been found in the lower Ruby Ranch at the Mill Canyon Dinosaur Tracksite north of Moab, Utah. These tracks are significant as they demonstrate that these dinosaurs walked on only two toes to keep their sickle-claw sharp.",
    "Deinonychus are from the middle cretaceous period.",
    "Your favorite dinosaur is the triceratops."
]



# 2) Embedding model + helpers
embedder = SentenceTransformer("all-MiniLM-L6-v2")

#keeps direction of the vector, but sets the length to 1
def normalize(vectors: np.ndarray) -> np.ndarray:
    """Row-wise L2 normalize a 2D numpy array."""
    norms = np.linalg.norm(vectors, axis=1, keepdims=True) + 1e-12
    return vectors / norms

# Precompute and normalize KB vectors once
kb_vectors = embedder.encode(knowledge_base, convert_to_numpy=True)
kb_vectors = normalize(kb_vectors)


# 3) model setup
# Model name just declares which model to load
MODEL_NAME = "google/flan-t5-base"

# AutoTokenizer.fromPretrained() creates a tokenizer with default settings from the model
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# AutoModelForSeq2SeqLM.from_pretrained() loads a sequence to sequence(encoder-decoder) model
# with default settings
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)



def generate_answer(prompt: str, max_new_tokens: int = 80) -> str:
    """Generate an answer from a seq2seq model (deterministic)."""
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)

    with torch.no_grad(): # saves memory by not saving previous states of the tensors
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,     # deterministic
            num_beams=1
        )

    return tokenizer.decode(output_ids[0], skip_special_tokens=True).strip()

# -----------------------------
# 4) Retrieval + Chat loop
# -----------------------------
TOP_K = 3
CONF_THRESHOLD = 0.45  # tune (0.35-0.60 typical)
DEBUG_SHOW_RETRIEVAL = False  # set True to print retrieved facts + scores

print("DinoNuggets is ready! Type your question or type 'exit' to quit.\n")

while True:
    try:
        question = input("You: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\n👋 Chatbot says goodbye!")
        break

    if question.lower() in {"exit", "quit"}:
        print("👋 Chatbot says goodbye!")
        break

    if not question:
        print("\nPlease type a question.\n")
        continue

    # Embed question and normalize
    q_vec = embedder.encode([question], convert_to_numpy=True)
    q_vec = normalize(q_vec)

    # Cosine similarity (dot product of normalized vectors)
    scores = (q_vec @ kb_vectors.T).flatten()

    # Retrieve top-k
    top_indices = np.argsort(scores)[::-1][:TOP_K]
    top_score = float(scores[top_indices[0]])

    if top_score < CONF_THRESHOLD:
        print("\n🤖 Chatbot says:\nI don’t know based on my knowledge base.\n")
        continue

    retrieved = [(knowledge_base[i], float(scores[i])) for i in top_indices]

    if DEBUG_SHOW_RETRIEVAL:
        print("\n[DEBUG] Retrieved facts:")
        for fact, sc in retrieved:
            print(f"  score={sc:.3f} | {fact}")
        print()

    context_block = "\n- " + "\n- ".join([fact for fact, _ in retrieved])

    prompt = (
        "You are a friendly dinosaur expert.\n"
        "Using the context below, provide a detailed and enthusiastic response in full sentences.\n"
        "If the answer is not in the context, reply exactly: "
        "\"I don’t know based on my knowledge base.\"\n\n"
        f"Context:{context_block}\n\n"
        f"Question: {question}\n"
        "Expert Answer: As a dinosaur expert, I can tell you that"
    )

    response = generate_answer(prompt, max_new_tokens=100)
    print("\nDinoNuggets says:\n", response, "\n")